#!/bin/bash

mkdir -p ../results/

#../../../_build/exec/pi-N/piN_Ndilep load[../../../lib/ELModel/model_params] dsig_dM srt=1.49 cutoff=ZM rhospec=0 Born \
#    N1440 N1520 N1535 res_rhophase=90 dM=0.001 gamma rho > ../results/piN_Ndilep_dsig_dM_srt1.49_90deg

#../../../_build/exec/pi-N/piN_Npipi load[../../../lib/ELModel/model_params] dsig_dM srt=1.49 cutoff=ZM rhospec=0 Born \
#    N1520 N1440 N1535 dM=0.01 rho > ../results/piN_Npipi_dsig_dM_srt1.49_all

../../../_build/exec/pi-N/pionPhotoprod load[../../../lib/ELModel/model_params] cutoff=ZM Born \
    D1232 N1520 N1440 N1535 dsrt=0.01 gamma > ../results/pionPhotoprod_all
